title: Adding a sprite from a file
hero_image: images/banner.png
description: Adding a sprite from a file in Scratch
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: 
technologies: "scratch"
steps:
  - title: Adding a sprite from a file
